services:
  - type: web
    name: learnova-backend-api
    runtime: node
    repo: https://github.com/Tanvir-Bhuiyan00/learnova_backend_server
    plan: free
    buildCommand: pnpm install && pnpm build
    startCommand: pnpm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: learnova-db
          property: connectionString
      - key: BETTER_AUTH_URL
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: GOOGLE_CALLBACK_URL
        sync: false
      - key: BETTER_AUTH_SECRET
        sync: false
      - key: ACCESS_TOKEN_SECRET
        sync: false
      - key: REFRESH_TOKEN_SECRET
        sync: false
      - key: ACCESS_TOKEN_EXPIRES_IN
        value: 1d
      - key: REFRESH_TOKEN_EXPIRES_IN
        value: 7d
      - key: BETTER_AUTH_SESSION_TOKEN_EXPIRES_IN
        value: 1d
      - key: BETTER_AUTH_SESSION_TOKEN_UPDATE_AGE
        value: 1d
      - key: EMAIL_SENDER_SMTP_USER
        sync: false
      - key: EMAIL_SENDER_SMTP_PASS
        sync: false
      - key: EMAIL_SENDER_SMTP_HOST
        sync: false
      - key: EMAIL_SENDER_SMTP_PORT
        sync: false
      - key: EMAIL_SENDER_SMTP_FROM
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      - key: SUPER_ADMIN_EMAIL
        sync: false
      - key: SUPER_ADMIN_PASSWORD
        sync: false

databases:
  - name: learnova-db
    plan: free
    databaseName: learnova
    postgresMajorVersion: 16
